development:
  adapter: mysql2
  reconnect: false
  database: griby
  pool: 5
  username: root
  password: gfcrfkm

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: griby_test
  pool: 5
  username: root
  password: gfcrfkm

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: griby
  pool: 5
  username: root
  password: gfcrfkm
